# Generated by Django 5.2.2 on 2025-06-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(default='123', max_length=20)),
                ('certificado', models.FileField(upload_to='certificados/')),
                ('institucion', models.CharField(choices=[('UChile', 'Universidad de Chile'), ('PUC', 'Pontificia Universidad Católica de Chile'), ('UCMaule', 'Universidad Católica del Maule'), ('UAustral', 'Universidad Austral de Chile'), ('UdeC', 'Universidad de Concepción'), ('UMayor', 'Universidad Mayor'), ('USS', 'Universidad San Sebastián'), ('UDLA', 'Universidad de Las Américas'), ('UBO', 'Universidad Bernardo O’Higgins'), ('UCTemuco', 'Universidad Católica de Temuco'), ('USTomas', 'Universidad Santo Tomás'), ('UVM', 'Universidad Viña del Mar'), ('UNAB', 'Universidad Nacional Andrés Bello'), ('DuocUC', 'Duoc UC'), ('IPValleCentral', 'Instituto Profesional Valle Central'), ('IDMA', 'Centro de Formación Técnica IDMA'), ('UAconcagua', 'Universidad de Aconcagua')], max_length=100)),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
    ]
